import { Job } from '../fake-apis/job-listing-apis';

const jobListing: Job[] = [
    {
        id: 'J-10001',
        companyName: 'Intuit',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '11/07/2022',
        createdBy: 'U-10004',
        salaryRange: [0, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
            'Ruby',
        ],
        applicants: ['U-10001', 'U-10002', 'U-10003'],
    },
    {
        id: 'J-10002',
        companyName: 'Rippling',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '12/07/2022',
        createdBy: 'U-10004',
        salaryRange: [3000000, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
        ],
        applicants: ['U-10003'],
    },
    {
        id: 'J-10003',
        companyName: 'Amazon',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '01/07/2022',
        createdBy: 'U-10005',
        salaryRange: [6000000, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
        ],
        applicants: [],
    },
    {
        id: 'J-10004',
        companyName: 'Google',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '10/07/2022',
        createdBy: 'U-10006',
        salaryRange: [0, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
            'Ruby',
        ],
        applicants: [],
    },
    {
        id: 'J-10005',
        companyName: 'Bolt',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '12/06/2022',
        createdBy: 'U-10005',
        salaryRange: [7050000, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
            'Dart',
        ],
        applicants: [],
    },
    {
        id: 'J-10006',
        companyName: 'Intuit',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '12/07/2021',
        createdBy: 'U-10005',
        salaryRange: [3000000, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
        ],
        applicants: [],
    },
    {
        id: 'J-10007',
        companyName: 'Netflix',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '18/07/2022',
        createdBy: 'U-10006',
        salaryRange: [0, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
        ],
        applicants: [],
    },
    {
        id: 'J-10008',
        companyName: 'Apple',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '19/07/2022',
        createdBy: 'U-10006',
        salaryRange: [0, 1000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
        ],
        applicants: [],
    },
    {
        id: 'J-10009',
        companyName: 'Zerodha',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '22/07/2022',
        createdBy: 'U-10004',
        salaryRange: [0, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
            'Ruby',
        ],
        applicants: [],
    },
    {
        id: 'J-10010',
        companyName: 'Tekion',
        title: 'Frontend Engineer - II',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit pellentesque habitant morbi tristique senectus et netus. Tristique et egestas quis ipsum suspendisse. In vitae turpis massa sed elementum tempus egestas. Sed faucibus turpis in eu mi bibendum neque egestas. Mattis enim ut tellus elementum sagittis vitae et leo duis. Rhoncus est pellentesque elit ullamcorper dignissim. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vel pharetra vel turpis nunc eget lorem dolor. Ipsum nunc aliquet bibendum enim facilisis. Cursus vitae congue mauris rhoncus. Volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla.',
        location: 'Bengaluru',
        createdAt: '02/07/2022',
        createdBy: 'U-10006',
        salaryRange: [0, 9000000],
        tags: [
            'CSS',
            'HTML',
            'Javascript',
            'React.js',
            'Typescript',
            'Next.js',
        ],
        applicants: [],
    },
];

export default jobListing;
